#!/usr/bin/env bash
#
# install_edge.sh — Set up HyperAgg client on Beelink / TP-Link / RPi
#
# Physical setup:
#   Laptop → (WiFi/ETH) → [THIS DEVICE] → Starlink (eth1) + Cellular (usb0) → VPS → Internet
#
# Run this on the Beelink:
#   bash install_edge.sh --vps-host <VPS_IP> --key <ENCRYPTION_KEY>
#
# Optional flags:
#   --wan-interfaces "eth1 usb0"     Override WAN interface detection
#   --lan-interface eth0             LAN port where laptop connects
#   --lan-ip 192.168.50.1           Gateway IP for LAN
#
# After running:
#   - Connected laptop uses Beelink as gateway (192.168.50.1)
#   - Dashboard: http://192.168.50.1:8080 from laptop browser
#   - All laptop traffic bonded across Starlink + cellular via VPS

set -euo pipefail

INSTALL_DIR="/opt/hyperagg"
CONFIG_FILE="$INSTALL_DIR/config.yaml"
SERVICE_NAME="hyperagg-client"

# Parse arguments
VPS_HOST=""
ENCRYPTION_KEY=""
WAN_INTERFACES=""
LAN_INTERFACE=""
LAN_IP="192.168.50.1"

while [[ $# -gt 0 ]]; do
    case $1 in
        --vps-host)     VPS_HOST="$2"; shift 2 ;;
        --key)          ENCRYPTION_KEY="$2"; shift 2 ;;
        --wan-interfaces) WAN_INTERFACES="$2"; shift 2 ;;
        --lan-interface)  LAN_INTERFACE="$2"; shift 2 ;;
        --lan-ip)         LAN_IP="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ -z "$VPS_HOST" ]; then
    echo "Usage: bash install_edge.sh --vps-host <VPS_IP> --key <KEY>"
    echo ""
    echo "Get the VPS IP and encryption key from the VPS install output."
    exit 1
fi

echo "=== HyperAgg Edge Installer ==="
echo "  VPS: $VPS_HOST"
echo "  LAN: ${LAN_INTERFACE:-auto} at ${LAN_IP}"
echo ""

# 1. System packages
echo "[1/5] Installing system dependencies..."
apt-get update -qq 2>/dev/null || true
apt-get install -y -qq python3 python3-pip git iproute2 iptables dnsmasq > /dev/null 2>&1 || true

# 2. Clone / update
echo "[2/5] Installing HyperAgg..."
if [ -d "$INSTALL_DIR" ]; then
    cd "$INSTALL_DIR"
    git pull --quiet 2>/dev/null || true
else
    git clone https://github.com/YX12399/ratan-engine.git "$INSTALL_DIR" 2>/dev/null || {
        mkdir -p "$INSTALL_DIR"
        echo "Git clone failed — copy files manually to $INSTALL_DIR"
    }
fi

cd "$INSTALL_DIR"

# 3. Python dependencies
echo "[3/5] Installing Python dependencies..."
pip3 install --quiet -r requirements.txt 2>/dev/null || pip3 install --quiet pyyaml cryptography reedsolo numpy scipy fastapi uvicorn websockets

# 4. Auto-detect WAN interfaces if not specified
if [ -z "$WAN_INTERFACES" ]; then
    echo "[4/5] Auto-detecting WAN interfaces..."
    # Find interfaces with IP addresses, excluding lo, hagg, docker, veth
    WAN_INTERFACES=$(ip -4 -o addr show | grep -v -E 'lo |hagg|docker|veth|br-' | awk '{print $2}' | sort -u | tr '\n' ' ')
    # Remove LAN interface from WAN list
    if [ -n "$LAN_INTERFACE" ]; then
        WAN_INTERFACES=$(echo "$WAN_INTERFACES" | sed "s/$LAN_INTERFACE//g" | xargs)
    fi
    echo "  Detected: $WAN_INTERFACES"
else
    echo "[4/5] Using specified WAN interfaces: $WAN_INTERFACES"
fi

# 5. Create config
echo "[5/5] Creating config..."

# Build WAN interfaces YAML list
WAN_YAML=""
for iface in $WAN_INTERFACES; do
    WAN_YAML="$WAN_YAML\n  - $iface"
done

cat > "$CONFIG_FILE" << YAML
# HyperAgg Edge Configuration — generated by install_edge.sh
# VPS: $VPS_HOST
# WAN: $WAN_INTERFACES

server:
  host: "0.0.0.0"
  port: 8080

vps:
  host: "$VPS_HOST"
  tunnel_port: 9999
  api_port: 8080
  encryption_key: "${ENCRYPTION_KEY}"
  server_ip: "10.99.0.2"
  client_ip: "10.99.0.1"

interfaces:
  wan_interfaces: $(echo -e "$WAN_YAML")

tunnel:
  mtu: 1400
  keepalive_interval_ms: 1000
  sequence_window: 1024
  reorder_timeout_ms: 100

fec:
  mode: "auto"
  xor_group_size: 4
  rs_data_shards: 8
  rs_parity_shards: 2
  replication_threshold: 0.15
  group_timeout_ms: 500

scheduler:
  mode: "ai"
  probe_interval_ms: 100
  history_window: 50
  prediction_horizon_ms: 200
  ewma_alpha: 0.3
  latency_budget_ms: 150
  jitter_weight: 0.3
  loss_weight: 0.5
  rtt_weight: 0.2

qos:
  enabled: true
  tiers:
    realtime:
      mark: 1
      bandwidth_pct: 60
      ports: "3478-3481"
      protocol: "udp"
      fec_mode: "replicate"
    streaming:
      mark: 2
      bandwidth_pct: 30
      ports: "5000-5010"
      fec_mode: "reed_solomon"
    bulk:
      mark: 3
      bandwidth_pct: 10
      fec_mode: "xor"
YAML

# Set up LAN DHCP if lan-interface specified
if [ -n "$LAN_INTERFACE" ]; then
    echo "Setting up LAN gateway on $LAN_INTERFACE ($LAN_IP)..."

    ip addr add "${LAN_IP}/24" dev "$LAN_INTERFACE" 2>/dev/null || true
    ip link set dev "$LAN_INTERFACE" up

    # Configure dnsmasq for DHCP on LAN
    cat > /etc/dnsmasq.d/hyperagg-lan.conf << DHCP
interface=$LAN_INTERFACE
dhcp-range=${LAN_IP%.*}.100,${LAN_IP%.*}.200,255.255.255.0,12h
dhcp-option=option:router,$LAN_IP
dhcp-option=option:dns-server,8.8.8.8,1.1.1.1
DHCP

    systemctl restart dnsmasq 2>/dev/null || true
    echo "  DHCP server running — laptops get IP from ${LAN_IP%.*}.100-200"
fi

# Build service command
SVC_CMD="/usr/bin/python3 -m hyperagg --mode client --config $CONFIG_FILE --api-port 8080"
if [ -n "$LAN_INTERFACE" ]; then
    SVC_CMD="$SVC_CMD --lan-interface $LAN_INTERFACE --lan-ip $LAN_IP"
fi

# Create systemd service
cat > "/etc/systemd/system/${SERVICE_NAME}.service" << SERVICE
[Unit]
Description=HyperAgg Bonding Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
ExecStart=$SVC_CMD
Restart=always
RestartSec=5
# Required for TUN device and SO_BINDTODEVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl start "$SERVICE_NAME"

echo ""
echo "=== HyperAgg Edge Node Ready ==="
echo ""
echo "  VPS:        $VPS_HOST (UDP 9999)"
echo "  WAN paths:  $WAN_INTERFACES"
if [ -n "$LAN_INTERFACE" ]; then
echo "  LAN:        $LAN_INTERFACE at $LAN_IP (DHCP enabled)"
echo "  Dashboard:  http://$LAN_IP:8080 (from laptop)"
echo ""
echo "  Connect your laptop to $LAN_INTERFACE and:"
echo "    1. Open http://$LAN_IP:8080 in browser"
echo "    2. All traffic is bonded through Starlink + Cellular"
else
echo "  Dashboard:  http://localhost:8080"
fi
echo ""
echo "  Service:    systemctl status $SERVICE_NAME"
echo "  Logs:       journalctl -u $SERVICE_NAME -f"
echo ""
