#!/usr/bin/env bash
#
# install_server.sh — Set up HyperAgg server on Hetzner VPS
#
# Run this on the VPS:
#   curl -sSL https://raw.githubusercontent.com/YX12399/ratan-engine/main/scripts/install_server.sh | bash
#   OR: scp this file to VPS and run: bash install_server.sh
#
# What this does:
#   1. Installs Python 3.11+ and dependencies
#   2. Generates an encryption key (shared with edge node)
#   3. Enables IP forwarding and NAT
#   4. Creates systemd service for auto-start
#   5. Starts HyperAgg server with dashboard on port 8080
#
# After running:
#   - Dashboard: http://<VPS_IP>:8080
#   - Tunnel port: UDP 9999
#   - Copy the generated key to your edge node's config.yaml

set -euo pipefail

INSTALL_DIR="/opt/hyperagg"
CONFIG_FILE="$INSTALL_DIR/config.yaml"
SERVICE_NAME="hyperagg-server"

echo "=== HyperAgg Server Installer ==="
echo ""

# 1. System packages
echo "[1/6] Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv git iptables iproute2 > /dev/null

# 2. Clone / update repo
echo "[2/6] Installing HyperAgg..."
if [ -d "$INSTALL_DIR" ]; then
    cd "$INSTALL_DIR"
    git pull --quiet 2>/dev/null || true
else
    git clone https://github.com/YX12399/ratan-engine.git "$INSTALL_DIR" 2>/dev/null || {
        mkdir -p "$INSTALL_DIR"
        echo "Git clone failed — copy files manually to $INSTALL_DIR"
    }
fi

cd "$INSTALL_DIR"

# 3. Python dependencies
echo "[3/6] Installing Python dependencies..."
pip3 install --quiet -r requirements.txt 2>/dev/null || pip3 install --quiet pyyaml cryptography reedsolo numpy scipy fastapi uvicorn websockets

# 4. Generate encryption key if not exists
if [ ! -f "$INSTALL_DIR/.hyperagg_key" ]; then
    echo "[4/6] Generating encryption key..."
    python3 -c "
import base64, os
key = os.urandom(32)
b64 = base64.b64encode(key).decode()
with open('$INSTALL_DIR/.hyperagg_key', 'w') as f:
    f.write(b64)
print(f'Key generated: {b64}')
print(f'COPY THIS KEY to your edge node config.yaml under vps.encryption_key')
"
else
    echo "[4/6] Encryption key already exists"
fi

ENCRYPTION_KEY=$(cat "$INSTALL_DIR/.hyperagg_key")

# 5. Create server config
echo "[5/6] Creating config..."
SERVER_IP=$(hostname -I | awk '{print $1}')

cat > "$CONFIG_FILE" << YAML
# HyperAgg Server Configuration — generated by install_server.sh
# VPS IP: $SERVER_IP

server:
  host: "0.0.0.0"
  port: 8080

vps:
  host: "$SERVER_IP"
  tunnel_port: 9999
  api_port: 8080
  encryption_key: "$ENCRYPTION_KEY"
  server_ip: "10.99.0.2"
  client_ip: "10.99.0.1"

interfaces:
  wan_interfaces: []

tunnel:
  mtu: 1400
  keepalive_interval_ms: 1000
  sequence_window: 1024
  reorder_timeout_ms: 100

fec:
  mode: "auto"
  xor_group_size: 4
  rs_data_shards: 8
  rs_parity_shards: 2
  replication_threshold: 0.15
  group_timeout_ms: 500

scheduler:
  mode: "ai"
  probe_interval_ms: 100
  history_window: 50
  prediction_horizon_ms: 200
  ewma_alpha: 0.3
  latency_budget_ms: 150
  jitter_weight: 0.3
  loss_weight: 0.5
  rtt_weight: 0.2

qos:
  enabled: true
  tiers:
    realtime:
      mark: 1
      bandwidth_pct: 60
      ports: "3478-3481"
      protocol: "udp"
      fec_mode: "replicate"
    streaming:
      mark: 2
      bandwidth_pct: 30
      ports: "5000-5010"
      fec_mode: "reed_solomon"
    bulk:
      mark: 3
      bandwidth_pct: 10
      fec_mode: "xor"
YAML

# 6. Enable IP forwarding + open firewall
echo "[6/6] Configuring network..."
sysctl -w net.ipv4.ip_forward=1 > /dev/null
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf 2>/dev/null || true

# Open UDP tunnel port
iptables -A INPUT -p udp --dport 9999 -j ACCEPT 2>/dev/null || true
# Open dashboard port
iptables -A INPUT -p tcp --dport 8080 -j ACCEPT 2>/dev/null || true

# Create systemd service
cat > "/etc/systemd/system/${SERVICE_NAME}.service" << SERVICE
[Unit]
Description=HyperAgg Bonding Server
After=network.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
ExecStart=/usr/bin/python3 -m hyperagg --mode server --config $CONFIG_FILE --api-port 8080
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl start "$SERVICE_NAME"

echo ""
echo "=== HyperAgg Server Ready ==="
echo ""
echo "  Dashboard:  http://$SERVER_IP:8080"
echo "  Tunnel:     UDP port 9999"
echo "  Config:     $CONFIG_FILE"
echo "  Service:    systemctl status $SERVICE_NAME"
echo "  Logs:       journalctl -u $SERVICE_NAME -f"
echo ""
echo "  IMPORTANT: Copy this key to your edge node config:"
echo "  encryption_key: $ENCRYPTION_KEY"
echo ""
